"use client";
import Link from "next/link";
import SiteShell, { SITE_CSS, SiteFont } from "../components/SiteShell";
const CSS = `
.detail-hero { padding: clamp(70px,10vw,140px) 0 65px; background:var(--ink); color:var(--pearl-white); }
.detail-hero .eyebrow { color:var(--warm-sand); } .detail-hero h1 { max-width:1000px; font-size:clamp(56px,8vw,115px); } .detail-hero a { display:inline-block; margin-bottom:32px; font-size:12px; text-transform:uppercase; letter-spacing:.15em; }
.detail-photo { width:100%; height:clamp(300px,65vw,750px); object-fit:cover; }
.detail-story { padding:clamp(60px,9vw,130px) 0; background:var(--pale-sand); } .detail-grid { display:grid; grid-template-columns:1fr 1fr; gap:8%; } .detail-grid h2 { font-size:clamp(42px,5vw,72px); } .detail-grid p { color:var(--muted); margin:0 0 32px; } .detail-spec { display:flex; justify-content:space-between; gap:20px; border-top:1px solid var(--line); padding:18px 0; font-size:14px; } .detail-spec span:first-child { color:var(--muted); } .detail-cta { display:inline-block; margin-top:32px; padding:16px 24px; background:var(--ink); color:var(--pearl-white); font-size:12px; text-transform:uppercase; letter-spacing:.12em; }
@media(max-width:700px) { .detail-grid { grid-template-columns:1fr; gap:30px; } .detail-spec { flex-direction:column; gap:8px; } }
`;
export default function CollectionDetail({item}) { return <><SiteFont/><style dangerouslySetInnerHTML={{__html:SITE_CSS+CSS}}/><SiteShell><section className="detail-hero"><div className="shell"><Link href="/collections">← All collections</Link><p className="eyebrow">{item.category}</p><h1 className="display">{item.name}</h1></div></section><img className="detail-photo" src={`https://images.unsplash.com/photo-${item.photo}?auto=format&fit=crop&q=85&w=1800`} alt={item.name}/><section className="detail-story"><div className="shell detail-grid"><div className="reveal"><p className="eyebrow">Considered in every detail</p><h2 className="display">{item.intro}</h2></div><div className="reveal"><p>{item.copy}</p><div className="detail-spec"><span>Materials</span><span>{item.material}</span></div><div className="detail-spec"><span>Finish</span><span>{item.finish}</span></div><div className="detail-spec"><span>Dimensions</span><span>Adapted to your space</span></div><Link className="detail-cta" href="/customisation">Make it personal →</Link></div></div></section></SiteShell></>; }
