"use client";
import Link from "next/link";
import SiteShell, { SITE_CSS, SiteFont } from "../components/SiteShell";
const items = [
["Can a piece be made to fit my room?", "The collection is imagined as a starting point. Dimensions, proportions, storage and finishes can be considered around your room and daily routines."],
["Where should I begin?", "Start with the room measurements, a few photographs and any references you like. The Customisation page explains the steps from a first idea to a considered design."],
["Can I choose the materials and finish?", "Yes. The concept includes a choice of timber expressions, surface finishes and upholstery. The right combination depends on the piece and how it will be used."],
["Are the photographs examples of completed orders?", "This is a portfolio website concept by Adloom. The imagery illustrates the design direction and is not presented as a record of commissioned work."],
["Can I place an order on this website?", "There is no checkout or payment collection. The contact form opens an email draft to Adloom for enquiries about this website concept."]];
export default function FAQ(){return <><SiteFont/><style dangerouslySetInnerHTML={{__html:SITE_CSS+` .faq-intro{background:var(--ink);color:var(--pearl-white);padding:100px 0 80px;text-align:center}.faq-intro h1{font-size:clamp(55px,8vw,110px)}.faq-body{background:var(--pale-sand);padding:80px 0}.faq-list{max-width:900px;margin:auto}.faq-list details{border-top:1px solid var(--line);padding:24px 0}.faq-list summary{cursor:pointer;font-size:clamp(20px,2.5vw,28px)}.faq-list p{max-width:700px;color:var(--muted);margin-top:20px}.faq-list a{display:inline-block;margin-top:36px;border-bottom:1px solid;padding-bottom:5px} `}}/><SiteShell><section className="faq-intro"><div className="shell"><p className="eyebrow">A little clarity</p><h1 className="display">Good questions.</h1></div></section><section className="faq-body"><div className="shell faq-list">{items.map(([question,answer])=><details key={question} className="reveal"><summary>{question}</summary><p>{answer}</p></details>)}<Link href="/contact">Start a conversation →</Link></div></section></SiteShell></>}
